name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: npm install --legacy-peer-deps --frozen-lockfile
      - name: Build
        run: npm run build
      - name: zip create
        run: zip -qq -r ./build.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://dantong-bucket/build.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name dantong-codeDeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name dantong-codeDeploy-group
          --s3-location bucket=dantong-bucket,bundleType=zip,key=build.zip
